### ISSUE TITLE
Defining experiments to run

### ISSUE THREAD

**Issue by Cinofix** [attackbench/AttackBench#7]
We already have the code necessary to run the experiments. Now we need to decide how we want to test and compare the attacks.

Firstly, in our previous discussion, we talked about running experiments with the default config and comparing different implementations of the same attack to find the most "reliable" library, if there is one. Are we still interested in conducting that kind of experiment? Also, do we care if the attack adapts its hyperparameters during optimization?

The second set of experiments involved comparing attacks based on their number of iterations. However, each attack interprets the num_steps parameter differently. For instance, C&W has an inner loop that uses more queries for each step. Therefore, relying on that parameter may not be feasible. One alternative solution is to wrap the model and set the forward/backward to 0 if the attack has reached the query limit. In this way, the attack iteration will stop after using the same number of queries, and we won't have to worry about how they use them. However, the downside of this approach is that we need to set the num_steps to a large number, causing the attack to spend more time on the GPU. Additionally, the overhead may lead to false results when comparing the running time of the attacks (if we care about it).

All these concerns can be justified in the paper, but I would like to hear your opinion on what you think is the most "fair" way to compare attacks.

@battistabiggio  @maurapintor @zangobot @jeromerony

**Comment by maurapintor** [comment]
Closing, solved with the paper.
